name: user_terminal_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  chopper: ^8.3.0

dev_dependencies:
  build_runner: ^2.7.0
  chopper_generator: ^8.3.1
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  lints: ^6.0.0
  test: ^1.25.6
